# superuser
sudo: required

language: java

# _________
# services we wish to use on our system:
services:
  - docker

# _________
# after the project has been successfully built.
after_success:
  - docker-compose up --abort-on-container-exit
